version: '3.8'

services:
  frontend:
    build:
      context: ./API-Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./apidemo
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/db_todo
    depends_on:
      - db-postgres

  service-node:
    build:
      context: ./express-aula1
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"

  db-postgres:
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: db_todo
    ports:
      - "5432:5432"

volumes:
  postgres_data: